/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.util.List;
import java.util.Arrays;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import Controllers.PetugasController;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class menuOfficers extends javax.swing.JPanel {

    private PetugasController p = new PetugasController();
    private DefaultTableModel view = new DefaultTableModel();

    /**
     * Creates new form menuCategory
     */
    public menuOfficers() {
        initComponents();
        index();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void index() {
        createIdPetugas.setText(p.autoIncrement());
        view.getDataVector().removeAllElements();
        view.fireTableDataChanged();

        if (tb_petugas.getColumnCount() == 0) {
            tb_petugas.setModel(view);
            view.addColumn("Id Petugas");
            view.addColumn("Nama Petugas");
            view.addColumn("Alamat");
            view.addColumn("Email");
            view.addColumn("Nomer Telpon");
        }

        List<String[]> data = p.index();
        for (String[] item : data) {
            view.addRow(new Object[]{
                item[0],
                item[1],
                item[2],
                item[3],
                item[4]
            });
        }
    }

    private void show(String kodePetugas) {
        createIdPetugas.setText(p.autoIncrement());
        view.getDataVector().removeAllElements();
        view.fireTableDataChanged();

        if (tb_petugas.getColumnCount() == 0) {
            tb_petugas.setModel(view);
            view.addColumn("Id Petugas");
            view.addColumn("Nama Petugas");
            view.addColumn("Alamat");
            view.addColumn("Email");
            view.addColumn("Nomer Telpon");
        }

        String[] item = p.show(kodePetugas);
        view.addRow(new Object[]{
            item[0],
            item[1],
            item[2],
            item[3],
            item[4]
        });
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_utama = new javax.swing.JPanel();
        pn_main = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_petugas = new javax.swing.JTable();
        btn_edit = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jLabel14 = new javax.swing.JLabel();
        indexKodePetugas = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        pn_add = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        createIdPetugas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        createAlamatPetugas = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        createTlpPetugas = new javax.swing.JTextField();
        createEmailPetugas = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        createNamaPetugas = new javax.swing.JTextField();
        pn_add1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        eKode = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        eAlamat = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        eTelpon = new javax.swing.JTextField();
        eEmail = new javax.swing.JTextField();
        btn_tambah3 = new javax.swing.JButton();
        btn_cancel3 = new javax.swing.JButton();
        eNama = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.CardLayout());

        pn_main.setBackground(new java.awt.Color(255, 255, 255));

        tb_petugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_petugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_petugasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_petugas);

        btn_edit.setBackground(new java.awt.Color(255, 255, 51));
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setText("Add New");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setText("Petugas");

        jLabel14.setText("Kode Petugas");

        btn_cari.setText("Cari Data");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_mainLayout = new javax.swing.GroupLayout(pn_main);
        pn_main.setLayout(pn_mainLayout);
        pn_mainLayout.setHorizontalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mainLayout.createSequentialGroup()
                .addGroup(pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_mainLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(indexKodePetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cari)
                        .addGap(18, 18, 18)
                        .addComponent(btn_refresh))
                    .addGroup(pn_mainLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_mainLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pn_mainLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(439, 439, 439))
        );
        pn_mainLayout.setVerticalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mainLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(indexKodePetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari)
                    .addComponent(btn_refresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pn_utama.add(pn_main, "card2");

        pn_add.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setText("Create Petugas");

        jLabel4.setText("ID Petugas");

        createIdPetugas.setEnabled(false);
        createIdPetugas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                createIdPetugasKeyTyped(evt);
            }
        });

        jLabel5.setText("Nama Petugas");

        jLabel6.setText("Alamat");

        createAlamatPetugas.setColumns(20);
        createAlamatPetugas.setRows(5);
        jScrollPane1.setViewportView(createAlamatPetugas);

        jLabel7.setText("Email");

        jLabel8.setText("Telepon");

        createTlpPetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTlpPetugasActionPerformed(evt);
            }
        });
        createTlpPetugas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                createTlpPetugasKeyTyped(evt);
            }
        });

        btn_tambah.setText("Save");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        jButton8.setText("Clear");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(createIdPetugas))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createTlpPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                                        .addComponent(createNamaPetugas)
                                        .addComponent(createEmailPetugas))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(btn_tambah)
                                .addGap(66, 66, 66)
                                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel2)))
                .addContainerGap(505, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(createIdPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(createNamaPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(36, 36, 36)))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(createEmailPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(createTlpPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_addLayout = new javax.swing.GroupLayout(pn_add);
        pn_add.setLayout(pn_addLayout);
        pn_addLayout.setHorizontalGroup(
            pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_addLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pn_addLayout.setVerticalGroup(
            pn_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_addLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pn_utama.add(pn_add, "card2");

        pn_add1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel27.setText("Edit Officer");

        jLabel28.setText("ID Petugas");

        eKode.setEnabled(false);
        eKode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                eKodeKeyTyped(evt);
            }
        });

        jLabel29.setText("Nama Petugas");

        jLabel30.setText("Alamat");

        eAlamat.setColumns(20);
        eAlamat.setRows(5);
        jScrollPane6.setViewportView(eAlamat);

        jLabel31.setText("Email");

        jLabel32.setText("Telepon");

        eTelpon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTelponActionPerformed(evt);
            }
        });
        eTelpon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                eTelponKeyTyped(evt);
            }
        });

        btn_tambah3.setText("Save");
        btn_tambah3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah3ActionPerformed(evt);
            }
        });

        btn_cancel3.setText("Cancel");
        btn_cancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(eKode))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(btn_tambah3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_cancel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                                        .addComponent(eNama)
                                        .addComponent(eEmail))))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(jLabel27)))
                .addContainerGap(505, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel27)
                .addGap(59, 59, 59)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(eKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(eNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addGap(36, 36, 36)))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(eEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(eTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cancel3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btn_tambah3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_add1Layout = new javax.swing.GroupLayout(pn_add1);
        pn_add1.setLayout(pn_add1Layout);
        pn_add1Layout.setHorizontalGroup(
            pn_add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_add1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pn_add1Layout.setVerticalGroup(
            pn_add1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_add1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pn_utama.add(pn_add1, "card2");

        add(pn_utama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        if ("".equals(indexKodePetugas.getText())) {
            JOptionPane.showMessageDialog(null, "Kode Jenis Tidak Ditemukan", "pesan kesalahan", JOptionPane.ERROR_MESSAGE);
        } else {
            String[] v = p.show(indexKodePetugas.getText());
            eKode.setText(v[0]);
            eNama.setText(v[1]);
            eAlamat.setText(v[2]);
            eEmail.setText(v[3]);
            eTelpon.setText(v[4]);
        }
        pn_utama.removeAll();
        pn_utama.add(pn_add1);
        pn_utama.repaint();
        pn_utama.revalidate();

    }//GEN-LAST:event_btn_editActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pn_utama.removeAll();
        pn_utama.add(pn_add);
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        if ("".equals(createIdPetugas.getText()) || "".equals(createNamaPetugas.getText())
                || "".equals(createAlamatPetugas.getText()) || "".equals(createEmailPetugas.getText()) || "".equals(createTlpPetugas.getText())) {
            JOptionPane.showMessageDialog(null, "Semua data wajib di isi!");
        } else {
            p.store(createNamaPetugas.getText(), createAlamatPetugas.getText(), createEmailPetugas.getText(), createTlpPetugas.getText());
            createIdPetugas.setText(p.autoIncrement());
            pn_utama.removeAll();
            pn_utama.add(pn_main);
            pn_utama.repaint();
            pn_utama.revalidate();
            index();
        }

    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        pn_utama.removeAll();
        pn_utama.add(pn_main);
        pn_utama.repaint();
        pn_utama.revalidate();
        createIdPetugas.setText(p.autoIncrement());
        createNamaPetugas.setText("");
        createAlamatPetugas.setText("");
        createEmailPetugas.setText("");
        createTlpPetugas.setText("");

    }//GEN-LAST:event_btn_cancelActionPerformed

    private void createIdPetugasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createIdPetugasKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume(); // Mencegah karakter yang bukan angka dimasukkan
            JOptionPane.showMessageDialog(null, "Hanya angka yang diperbolehkan", "Pesan Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createIdPetugasKeyTyped

    private void createTlpPetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTlpPetugasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_createTlpPetugasActionPerformed

    private void createTlpPetugasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createTlpPetugasKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String text = createTlpPetugas.getText();

        if (text.length() >= 12) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Masukan Hanya 12 angka bang gaboleh lebih !!!", "pesan kesalahan ", JOptionPane.ERROR_MESSAGE);
        }
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume(); // Mencegah karakter yang bukan angka dimasukkan
            JOptionPane.showMessageDialog(null, "Hanya angka yang diperbolehkan", "Pesan Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createTlpPetugasKeyTyped

    private void tb_petugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_petugasMouseClicked
        // TODO add your handling code here:
        int baris = tb_petugas.getSelectedRow();

        if (baris == -1) {
            return;
        }

        String id = tb_petugas.getValueAt(baris, 0).toString();
        indexKodePetugas.setText(id);
    }//GEN-LAST:event_tb_petugasMouseClicked

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        if ("".equals(indexKodePetugas.getText())) {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan !!!", "pesan kesalahan", JOptionPane.ERROR_MESSAGE);
            index();
        } else {
            show(indexKodePetugas.getText());
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        // TODO add your handling code here:
        index();
        indexKodePetugas.setText("");
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void eKodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eKodeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_eKodeKeyTyped

    private void eTelponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTelponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eTelponActionPerformed

    private void eTelponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eTelponKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_eTelponKeyTyped

    private void btn_tambah3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah3ActionPerformed
        // TODO add your handling code here:
        if ("".equals(eKode.getText()) || "".equals(eNama.getText()) || "".equals(eAlamat.getText()) || "".equals(eEmail.getText()) || "".equals(eTelpon.getText())) {
            JOptionPane.showMessageDialog(null, "Semua data Hasrus");
        } else {
            p.update(eKode.getText(), eNama.getText(), eAlamat.getText(), eEmail.getText(), eTelpon.getText());
            index();
            pn_utama.removeAll();
            pn_utama.add(pn_main);
            pn_utama.repaint();
            pn_utama.revalidate();
            indexKodePetugas.setText("");
        }
    }//GEN-LAST:event_btn_tambah3ActionPerformed

    private void btn_cancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancel3ActionPerformed
        // TODO add your handling code here:
        pn_utama.removeAll();
        pn_utama.add(pn_main);
        pn_utama.repaint();
        pn_utama.revalidate();
        indexKodePetugas.setText("");
    }//GEN-LAST:event_btn_cancel3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if ("".equals(indexKodePetugas.getText())) {
            JOptionPane.showMessageDialog(null, "Tidak ada Kode Petugas yang di pilih");
        } else {
            p.delete(indexKodePetugas.getText());
            index();
            indexKodePetugas.setText("");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        createIdPetugas.setText(p.autoIncrement());
        createNamaPetugas.setText("");
        createAlamatPetugas.setText("");
        createEmailPetugas.setText("");
        createTlpPetugas.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_cancel3;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_tambah3;
    private javax.swing.JTextArea createAlamatPetugas;
    private javax.swing.JTextField createEmailPetugas;
    private javax.swing.JTextField createIdPetugas;
    private javax.swing.JTextField createNamaPetugas;
    private javax.swing.JTextField createTlpPetugas;
    private javax.swing.JTextArea eAlamat;
    private javax.swing.JTextField eEmail;
    private javax.swing.JTextField eKode;
    private javax.swing.JTextField eNama;
    private javax.swing.JTextField eTelpon;
    private javax.swing.JTextField indexKodePetugas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private java.awt.Label label1;
    private javax.swing.JPanel pn_add;
    private javax.swing.JPanel pn_add1;
    private javax.swing.JPanel pn_main;
    private javax.swing.JPanel pn_utama;
    private javax.swing.JTable tb_petugas;
    // End of variables declaration//GEN-END:variables
}
