/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.awt.Color;
//import Controllers.countController;
//import Controllers.BarangMasukController;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Lenovo
 */
public class menuUtama extends javax.swing.JFrame {

//    private countController count = new countController();
//    private BarangMasukController b = new BarangMasukController();
    private DefaultTableModel view = new DefaultTableModel();
    /**
     * Creates new form menuUtama
     */
    public menuUtama() {
        initComponents();
      //  loadData();
    }

//    private void loadData() {
//        view.getDataVector().removeAllElements();
//        view.fireTableDataChanged();
//
//        if (tbBarangMasuk.getColumnCount() == 0) {
//            tbBarangMasuk.setModel(view);
//            view.addColumn("Nomer Nota");
//            view.addColumn("Nama Barang");
//            view.addColumn("Tanggal Masuk");
//            view.addColumn("Nama Distributor");
//            view.addColumn("Nama Petugas");
//            view.addColumn("Total");
//        }
//        
//        for (String[] v : b.Index()) {
//            view.addRow(new Object[]{
//                v[0],
//                v[1],
//                v[2],
//                v[3],
//                v[4],
//                v[5]
//            });
//        }
//        
//        countPetugas.setText(count.petugas());
//        countDistributor.setText(count.distributor());
//        countBarang.setText(count.barang());
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pn_kiri1 = new javax.swing.JPanel();
        p_main = new javax.swing.JPanel();
        p_ci = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_category = new javax.swing.JLabel();
        p_main1 = new javax.swing.JPanel();
        p_line1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JLabel();
        p_main2 = new javax.swing.JPanel();
        p_i = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_item = new javax.swing.JLabel();
        p_main3 = new javax.swing.JPanel();
        p_0 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btn_officer = new javax.swing.JLabel();
        p_main4 = new javax.swing.JPanel();
        p_c = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btn_customer = new javax.swing.JLabel();
        p_main5 = new javax.swing.JPanel();
        p_ii = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btn_incoming = new javax.swing.JLabel();
        p_main6 = new javax.swing.JPanel();
        p_d = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btn_distributor = new javax.swing.JLabel();
        p_main7 = new javax.swing.JPanel();
        p_d1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btn_distributor1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        countPetugas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBarangMasuk = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        countDistributor = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        countBarang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_kiri.setBackground(new java.awt.Color(255, 255, 255));
        pn_kiri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/shopping-cart.png"))); // NOI18N
        pn_kiri.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 38, 42, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("MY MARKET");
        pn_kiri.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 38, 132, 32));

        pn_kiri1.setBackground(new java.awt.Color(255, 255, 255));
        pn_kiri1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        pn_kiri1.setForeground(new java.awt.Color(255, 255, 255));

        p_main.setBackground(new java.awt.Color(255, 255, 255));

        p_ci.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout p_ciLayout = new javax.swing.GroupLayout(p_ci);
        p_ci.setLayout(p_ciLayout);
        p_ciLayout.setHorizontalGroup(
            p_ciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        p_ciLayout.setVerticalGroup(
            p_ciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/file (1).png"))); // NOI18N

        btn_category.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_category.setText("Jenis Barang");
        btn_category.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_categoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_categoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_categoryMouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_mainLayout = new javax.swing.GroupLayout(p_main);
        p_main.setLayout(p_mainLayout);
        p_mainLayout.setHorizontalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_ci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_category, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
        );
        p_mainLayout.setVerticalGroup(
            p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_mainLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(p_ci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_category, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        p_main1.setBackground(new java.awt.Color(255, 255, 255));
        p_main1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        p_line1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout p_line1Layout = new javax.swing.GroupLayout(p_line1);
        p_line1.setLayout(p_line1Layout);
        p_line1Layout.setHorizontalGroup(
            p_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        p_line1Layout.setVerticalGroup(
            p_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dashboard.png"))); // NOI18N

        btn_dashboard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_main1Layout = new javax.swing.GroupLayout(p_main1);
        p_main1.setLayout(p_main1Layout);
        p_main1Layout.setHorizontalGroup(
            p_main1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
        );
        p_main1Layout.setVerticalGroup(
            p_main1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main1Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(p_main1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_main1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_dashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        p_main2.setBackground(new java.awt.Color(255, 255, 255));

        p_i.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout p_iLayout = new javax.swing.GroupLayout(p_i);
        p_i.setLayout(p_iLayout);
        p_iLayout.setHorizontalGroup(
            p_iLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        p_iLayout.setVerticalGroup(
            p_iLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/product.png"))); // NOI18N

        btn_item.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_item.setText("Barang");
        btn_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_itemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_itemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_itemMouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_main2Layout = new javax.swing.GroupLayout(p_main2);
        p_main2.setLayout(p_main2Layout);
        p_main2Layout.setHorizontalGroup(
            p_main2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_i, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(btn_item, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
        );
        p_main2Layout.setVerticalGroup(
            p_main2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main2Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(p_main2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_i, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_main2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_item, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        p_main3.setBackground(new java.awt.Color(255, 255, 255));

        p_0.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout p_0Layout = new javax.swing.GroupLayout(p_0);
        p_0.setLayout(p_0Layout);
        p_0Layout.setHorizontalGroup(
            p_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        p_0Layout.setVerticalGroup(
            p_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/support.png"))); // NOI18N

        btn_officer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_officer.setText("Petugas");
        btn_officer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_officerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_officerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_officerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_main3Layout = new javax.swing.GroupLayout(p_main3);
        p_main3.setLayout(p_main3Layout);
        p_main3Layout.setHorizontalGroup(
            p_main3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(btn_officer, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        p_main3Layout.setVerticalGroup(
            p_main3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main3Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(p_main3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_main3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_officer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        p_main4.setBackground(new java.awt.Color(255, 255, 255));

        p_c.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout p_cLayout = new javax.swing.GroupLayout(p_c);
        p_c.setLayout(p_cLayout);
        p_cLayout.setHorizontalGroup(
            p_cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        p_cLayout.setVerticalGroup(
            p_cLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loan.png"))); // NOI18N

        btn_customer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_customer.setText("Penjualan");
        btn_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_customerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_customerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_customerMouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_main4Layout = new javax.swing.GroupLayout(p_main4);
        p_main4.setLayout(p_main4Layout);
        p_main4Layout.setHorizontalGroup(
            p_main4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_customer, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
        );
        p_main4Layout.setVerticalGroup(
            p_main4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main4Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(p_main4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_main4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_customer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        p_main5.setBackground(new java.awt.Color(255, 255, 255));

        p_ii.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout p_iiLayout = new javax.swing.GroupLayout(p_ii);
        p_ii.setLayout(p_iiLayout);
        p_iiLayout.setHorizontalGroup(
            p_iiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        p_iiLayout.setVerticalGroup(
            p_iiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/box.png"))); // NOI18N

        btn_incoming.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_incoming.setText("Barang Masuk");
        btn_incoming.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_incomingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_incomingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_incomingMouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_main5Layout = new javax.swing.GroupLayout(p_main5);
        p_main5.setLayout(p_main5Layout);
        p_main5Layout.setHorizontalGroup(
            p_main5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_ii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_incoming, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
        );
        p_main5Layout.setVerticalGroup(
            p_main5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main5Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(p_main5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_ii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_main5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_incoming, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        p_main6.setBackground(new java.awt.Color(255, 255, 255));

        p_d.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout p_dLayout = new javax.swing.GroupLayout(p_d);
        p_d.setLayout(p_dLayout);
        p_dLayout.setHorizontalGroup(
            p_dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        p_dLayout.setVerticalGroup(
            p_dLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/box (1).png"))); // NOI18N

        btn_distributor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_distributor.setText("Distribusi");
        btn_distributor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_distributorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_distributorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_distributorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_main6Layout = new javax.swing.GroupLayout(p_main6);
        p_main6.setLayout(p_main6Layout);
        p_main6Layout.setHorizontalGroup(
            p_main6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(12, 12, 12)
                .addComponent(btn_distributor, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
        );
        p_main6Layout.setVerticalGroup(
            p_main6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main6Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(p_main6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_main6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_distributor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        p_main7.setBackground(new java.awt.Color(255, 255, 255));

        p_d1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout p_d1Layout = new javax.swing.GroupLayout(p_d1);
        p_d1.setLayout(p_d1Layout);
        p_d1Layout.setHorizontalGroup(
            p_d1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        p_d1Layout.setVerticalGroup(
            p_d1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/box (1).png"))); // NOI18N

        btn_distributor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_distributor1.setText("Laporan");
        btn_distributor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_distributor1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_distributor1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_distributor1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout p_main7Layout = new javax.swing.GroupLayout(p_main7);
        p_main7.setLayout(p_main7Layout);
        p_main7Layout.setHorizontalGroup(
            p_main7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_main7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(12, 12, 12)
                .addComponent(btn_distributor1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
        );
        p_main7Layout.setVerticalGroup(
            p_main7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_main7Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(p_main7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_main7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btn_distributor1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout pn_kiri1Layout = new javax.swing.GroupLayout(pn_kiri1);
        pn_kiri1.setLayout(pn_kiri1Layout);
        pn_kiri1Layout.setHorizontalGroup(
            pn_kiri1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiri1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_kiri1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_main1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_main2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_main3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_main4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_main5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_main6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_main7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pn_kiri1Layout.setVerticalGroup(
            pn_kiri1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiri1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(p_main1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p_main2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p_main3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p_main4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p_main5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p_main6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(p_main7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pn_kiri1);
        pn_kiri1.getAccessibleContext().setAccessibleDescription("");

        pn_kiri.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 115, -1, 455));

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setPreferredSize(new java.awt.Dimension(726, 602));
        pn_utama.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(726, 602));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Petugas");

        countPetugas.setForeground(new java.awt.Color(255, 255, 255));
        countPetugas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countPetugas.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(countPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(countPetugas)
                .addGap(18, 18, 18))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 150, 80));

        tbBarangMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbBarangMasuk);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 620, 290));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("History Incoming Item");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 160, -1));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Distributor");

        countDistributor.setForeground(new java.awt.Color(255, 255, 255));
        countDistributor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countDistributor.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(countDistributor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(6, 6, 6)
                .addComponent(countDistributor)
                .addGap(18, 18, 18))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Barang");

        countBarang.setForeground(new java.awt.Color(255, 255, 255));
        countBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        countBarang.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(countBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(6, 6, 6)
                .addComponent(countBarang)
                .addGap(18, 18, 18))
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        pn_utama.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_utama, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_utama, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_categoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categoryMouseClicked
        // TODO add your handling code here:
        p_ci.setBackground(new Color(255, 255, 255));
        pn_utama.removeAll();
        pn_utama.add(new menuCategory());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_categoryMouseClicked

    private void btn_categoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categoryMouseEntered
        //   p_main.setBackground(new Color(250, 250, 250));
        p_ci.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_categoryMouseEntered

    private void btn_categoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categoryMouseExited
        //   p_main.setBackground(new Color(255, 255, 255));
        p_ci.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_categoryMouseExited

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        // TODO add your handling code here:
        p_line1.setBackground(new Color(0, 102, 153));
        pn_utama.removeAll();
        pn_utama.add(new menuDashboard());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        // TODO add your handling code here:
        p_line1.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
        // TODO add your handling code here:
        p_line1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemMouseClicked
        // TODO add your handling code here:
        p_i.setBackground(new Color(255, 255, 255));
        pn_utama.removeAll();
        pn_utama.add(new menuItems());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_itemMouseClicked

    private void btn_itemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemMouseEntered
        // TODO add your handling code here:
        p_i.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_itemMouseEntered

    private void btn_itemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_itemMouseExited
        // TODO add your handling code here:
        p_i.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_itemMouseExited

    private void btn_officerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_officerMouseClicked
        // TODO add your handling code here:
        p_0.setBackground(new Color(255, 255, 255));
        pn_utama.removeAll();
        pn_utama.add(new menuOfficers());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_officerMouseClicked

    private void btn_officerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_officerMouseEntered
        // TODO add your handling code here:
        p_0.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_officerMouseEntered

    private void btn_officerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_officerMouseExited
        // TODO add your handling code here:
        p_0.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_officerMouseExited

    private void btn_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_customerMouseClicked
        // TODO add your handling code here:
        p_c.setBackground(new Color(255, 255, 255));
        pn_utama.removeAll();
        pn_utama.add(new menuPenjualan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_customerMouseClicked

    private void btn_customerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_customerMouseEntered
        // TODO add your handling code here:
        p_c.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_customerMouseEntered

    private void btn_customerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_customerMouseExited
        // TODO add your handling code here:
        p_c.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_customerMouseExited

    private void btn_incomingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_incomingMouseClicked
        // TODO add your handling code here:
        p_ii.setBackground(new Color(255, 255, 255));
        pn_utama.removeAll();
        pn_utama.add(new menuBarangMasuk());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_incomingMouseClicked

    private void btn_incomingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_incomingMouseEntered
        // TODO add your handling code here:
        p_ii.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_incomingMouseEntered

    private void btn_incomingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_incomingMouseExited
        // TODO add your handling code here:
        p_ii.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_incomingMouseExited

    private void btn_distributorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_distributorMouseClicked
        // TODO add your handling code here:
        p_d.setBackground(new Color(255, 255, 255));
        pn_utama.removeAll();
        pn_utama.add(new menuDistributors());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_distributorMouseClicked

    private void btn_distributorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_distributorMouseEntered
        // TODO add your handling code here:
        p_d.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_distributorMouseEntered

    private void btn_distributorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_distributorMouseExited
        // TODO add your handling code here:
        p_d.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_distributorMouseExited

    private void btn_distributor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_distributor1MouseClicked
        // TODO add your handling code here:
        p_d.setBackground(new Color(255, 255, 255));
        pn_utama.removeAll();
        pn_utama.add(new menuLaporan());
        pn_utama.repaint();
        pn_utama.revalidate();
    }//GEN-LAST:event_btn_distributor1MouseClicked

    private void btn_distributor1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_distributor1MouseEntered
        // TODO add your handling code here:
        p_d.setBackground(new Color(0, 102, 153));
    }//GEN-LAST:event_btn_distributor1MouseEntered

    private void btn_distributor1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_distributor1MouseExited
        // TODO add your handling code here:
        p_d.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_distributor1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_category;
    private javax.swing.JLabel btn_customer;
    private javax.swing.JLabel btn_dashboard;
    private javax.swing.JLabel btn_distributor;
    private javax.swing.JLabel btn_distributor1;
    private javax.swing.JLabel btn_incoming;
    private javax.swing.JLabel btn_item;
    private javax.swing.JLabel btn_officer;
    private javax.swing.JLabel countBarang;
    private javax.swing.JLabel countDistributor;
    private javax.swing.JLabel countPetugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel p_0;
    private javax.swing.JPanel p_c;
    private javax.swing.JPanel p_ci;
    private javax.swing.JPanel p_d;
    private javax.swing.JPanel p_d1;
    private javax.swing.JPanel p_i;
    private javax.swing.JPanel p_ii;
    private javax.swing.JPanel p_line1;
    private javax.swing.JPanel p_main;
    private javax.swing.JPanel p_main1;
    private javax.swing.JPanel p_main2;
    private javax.swing.JPanel p_main3;
    private javax.swing.JPanel p_main4;
    private javax.swing.JPanel p_main5;
    private javax.swing.JPanel p_main6;
    private javax.swing.JPanel p_main7;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_kiri1;
    private javax.swing.JPanel pn_utama;
    private javax.swing.JTable tbBarangMasuk;
    // End of variables declaration//GEN-END:variables
}
